# Site settings
title: MADspace - Hackerspace Eindhoven
url: "https://madspace.nl"

description: MADspace. De eerste officiële hackerspace in Eindhoven. Opgericht op 25 juli 2013 te Eindhoven.
keywords: stichting, madspace, foundation, home, hackerspace, eindhoven, bestuur, contact

# Build settings
markdown: kramdown
future: true

collections:
  events:
    output: true
  deelnemers:
    output: true
  projecten:
    output: true
  securityProjects:
    output: true
